version: '3.4'

x-base:
  &base
  image: sentry:9.1.2
  restart: always
  command: sentry run web
  volumes:
    - ./data/app:/var/lib/sentry/files
  logging:
    options:
      max-size: "256M"
      max-file: "5"
  depends_on:
    - redis
    - postgres
  env_file:
    - .env

services:
  web:
    <<: *base
    ports:
      - 80:9000
      - 443:9000
    command: sentry run web
  worker:
    <<: *base
    command: sentry run worker -l info -c 4
  beat:
    <<: *base
    command: sentry run cron -l info
  test:
    <<: *base
    command: tail -F /tmp/xxx.log
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./data/redis:/data
  postgres:
    image: postgres:9-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SENTRY_DB_NAME}
      POSTGRES_PASSWORD: ${SENTRY_DB_USER}
      POSTGRES_USER: ${SENTRY_DB_PASSWORD}
